export AWS_ACCESS_KEY_ID="****"
echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY="****"
echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN="****"
echo AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
export AWS_DEFAULT_REGION="****"
echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
